name: movie_app
description: A simple movie app with trending and recommended movies.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Core Networking ---
  http: ^1.3.0
  dio: ^5.8.0+1
  html: ^0.15.4
  universal_html: ^2.2.4

  # --- UI & Design ---
  cupertino_icons: ^1.0.6
  intl: ^0.20.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  animate_do: ^4.2.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  emoji_picker_flutter: ^4.3.0
  visibility_detector: ^0.4.0+2
  palette_generator: ^0.3.3

  # --- Video & Media ---
  video_player: ^2.7.0
  better_player:
    path: ./better_player_fixed   # ✅ Local patched version
  youtube_player_flutter: ^9.1.1
  flutter_sound: ^9.2.13
  just_audio: ^0.10.4
  just_waveform: ^0.0.7
  fl_pip: ^3.2.1

  # --- Device Features ---
  screen_brightness: ^2.1.0
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^12.0.0+1
  vibration: ^3.1.3 
  network_info_plus: ^5.0.3 
  device_info_plus: ^11.5.0
  flutter_callkit_incoming: ^2.5.8
  system_info: ^1.0.1
  flutter_local_notifications: ^19.4.2

  # --- Storage & Database ---
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2

  # --- Firebase & Auth ---
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_auth_web: ^6.0.0
  google_sign_in: ^6.1.4
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.0.0
  firebase_app_check: ^0.4.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_database: ^12.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  cloud_functions: ^6.0.0

  # --- Ads & Monetization ---
  google_mobile_ads: ^6.0.0
  unity_ads_plugin: ^0.3.27
  # --- Realtime & Backend ---
  supabase_flutter: ^2.0.0
  livekit_client: ^2.5.0+hotfix.1
  shelf: ^1.4.2
  shelf_static: ^1.1.2

  # --- Web & Sharing ---
  webview_flutter: ^4.11.0
  flutter_inappwebview: ^6.1.5
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.4

  # --- Utils & Security ---
  uuid: ^4.5.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  pointycastle: ^3.4.0
  dartz: ^0.10.0
  dart_jsonwebtoken: ^2.14.0
  jose: ^0.3.3 
  googleapis_auth: ^1.6.0
  logging: ^1.2.0
  logger: ^2.0.2
  stream_transform: ^2.0.0

  # --- Downloads ---
  flutter_downloader: ^1.12.0

  # --- State Management ---
  provider: ^6.1.4

  # --- Sensors ---
  sensors_plus: ^6.1.1

  # --- WebRTC ---
  flutter_webrtc: ^1.0.0

  # --- Math & Transforms (needed for Matrix4) ---
  vector_math: ^2.1.4
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^8.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true  # ✅ Enables localization generation

  assets:
    - assets/icon/movieflixiconv1.png
    - assets/profile1.jpg
    - assets/profile2.jpg
    - assets/profile3.webp
    - assets/profile4.jpg
    - assets/profile5.jpg
    - assets/background1.jpg
    - assets/background2.jpg
    - assets/background3.webp
    - assets/background4.jpg
    - assets/background5.jpg
    - assets/googlelogo1.png
    - assets/marketplace_banner.png
    - assets/icon/indiefilm.jpg
    - assets/icon/premierticket.jpg
    - assets/icon/movieposter.jpg
    - assets/cinema.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/movieflixiconv1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/movieflixiconv1.png"
