// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWDbhdeFhA-nT270a1H5bw8duQYnKLdfU',
    authDomain: 'movieflix-53a51.firebaseapp.com',
    projectId: 'movieflix-53a51',
    storageBucket: 'movieflix-53a51.firebasestorage.app',
    messagingSenderId: '763430098943',
    appId: '1:763430098943:web:4aa8a467e530d7ea2379ca',
    measurementId: 'G-VFT3237KJ9'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOL8TqYuZCtgD5-Y6WX_eaD528FdFIqbM',
    appId: '1:763430098943:android:1b33af1e75ffd0ba2379ca',
    messagingSenderId: '763430098943',
    projectId: 'movieflix-53a51',
    storageBucket: 'movieflix-53a51.firebasestorage.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFMDN3vE2HFNa6kUpKO3N04lMpbV8wCow',
    iosBundleId: 'com.example.movieflix',
    appId: '1:763430098943:ios:79a0827577c415d42379ca',
    storageBucket: 'movieflix-53a51.firebasestorage.app',
    messagingSenderId: '763430098943',
    iosClientId: 'undefined',
    projectId: 'movieflix-53a51'
  );
}
